try:
    a+5
    print(a)#intenta ejecutar esto
except:
    print("ERROR")#ejecuta esto en caso de error en 
